// ===============================================
// EXPECTED FUNCTIONS - Chatbot / Langchain Module
// ===============================================
//
// Function: generateTextEmbedding(text)
// - Params: text (string)
// - Returns: an array representing the embedding vector, or { error }
// - Description: Creates an instance of OpenAIEmbeddings and calls embedQuery(text)
//   to generate a text embedding for the input string.
//
// Function: storeTextEmbeddingInChroma(id, vector, metadata)
// - Params: 
//       id: a unique identifier (string),
//       vector: an array of numbers,
//       metadata: an object containing { type, content, ... }
// - Returns: { success } or { error }
// - Description: Stores the generated text embedding along with metadata 
//   into a specific ChromaDB collection for later retrieval.
//
// Function: queryTextEmbedding(vector)
// - Params: vector (array)
// - Returns: An array of matching objects: [{ id, metadata, score }, ...]
// - Description: Queries the ChromaDB collection to find top-matching items using
//   cosine similarity and returns a ranked list.
//
// Function: generatePrompt(context, question)
// - Params: context (string), question (string)
// - Returns: A fully formed prompt string
// - Description: Fills in a template:
//     "Answer the question based on the following context:
//      Context: {context}
//      Question: {question}
//      Answer:"
//   to prepare the query for the LLM.
//
// Function: callLLM(prompt)
// - Params: prompt (string)
// - Returns: The response from the LLM as a string, or { error }
// - Description: Sends the prompt to OpenAI (or another LLM) and returns the generated answer.
//
// Function: answerQuestion(question)
// - Params: question (string)
// - Returns: Answer string generated by running the full pipeline:
//   (generateTextEmbedding → queryTextEmbedding → generatePrompt → callLLM)
// - Description: Implements the end-to-end process for answering a user's question
//   using retrieval augmented generation.
//
// ===============================================
